### ISSUE TITLE
Dashboard: Inventory Summary Does Not Show Correct Contents

### ISSUE THREAD

**Issue by christine-sm** [rubyforgood/pdx_diaper#37]
On [localhost:3000/dashboard](http://localhost:3000/dashboard):
<img width="519" alt="screen shot 2016-06-19 at 9 57 13 am" src="https://cloud.githubusercontent.com/assets/15206696/16177785/825b8e58-3604-11e6-8ecd-c15087ba8425.png">

**Comment by tmobaird** [comment]
I'll take this as well. I've been working on the stats on the dashboard, so I might as well take this unless someone else wants to

**Comment by armahillo** [comment]
I've got a commit in progress on this one - I'll push it up so that you can finish it off.

**Comment by tmobaird** [comment]
@armahillo awesome :+1:. I'll finish the dashboard Donation total stats when I get a chance

**Comment by tmobaird** [comment]
@armahillo what exactly do we want to display in the Inventory Summary panel on the dashboard?

**Comment by armahillo** [comment]
@tmobaird 
If you can just get the inventory table to show the current totals at each location (it's _mostly_ there but needs some massaging to make the bits show up under the correct column). It's kinda messy right now but the heavy lifting is post-query so it's at least not hammering the DB too hard (or shouldn't be!)

![5e82f859acec0d6c4a5c1cb451912dcd](https://cloud.githubusercontent.com/assets/502363/16364958/601703be-3bc1-11e6-9d05-380be00114a1.png)

**Comment by armahillo** [comment]
@cattywampus Merged and added my fixes afterwards. 

I reworked a couple of the helper methods to accept arrays for the first argument -- it's backwards compatible -- there MIGHT be redundancies introduced by this (ie. we might be able to DRY up the helper file further) but it now does more efficient WHERE clausing by passing an array when provided. AREL FTW. :+1: 

I think we can close this!

There's one outstanding issue that I'll create separately -- the day-by-day chart does a created_at query that scopes to individual day date ranges, and I'm not sure how to make that query more efficient, if that's even possible.
