### ISSUE TITLE
Filters on Index Pages: Current Filters displays 'None' when there is a filter applied

### ISSUE THREAD

**Issue by christine-sm** [rubyforgood/pdx_diaper#41]
Current view:
<img width="1036" alt="screen shot 2016-06-19 at 10 29 52 am" src="https://cloud.githubusercontent.com/assets/15206696/16177941/fb379d18-3608-11e6-9464-753f9e62e9ce.png">
However, "Current Filter" should list the filters that have been applied rather than the word "none". This is an issue across multiple index views (e.g. items, barcodes).

**Comment by armahillo** [comment]
This appears to be re known bug in ActiveAdmin: 
https://github.com/activeadmin/activeadmin/issues/4342

The fix is to `bundle update active_admin` to version 1.0.0-pre2  [TODO]
