### ISSUE TITLE
Filters on Index Pages: End Date is exclusive rather than inclusive

### ISSUE THREAD

**Issue by christine-sm** [rubyforgood/pdx_diaper#42]
All of these items were created on 6/19:
Filter 6/18-6/20 displays items
<img width="1053" alt="screen shot 2016-06-19 at 10 40 03 am" src="https://cloud.githubusercontent.com/assets/15206696/16177990/5eca17e2-360a-11e6-96a7-0bd5f3bcd7de.png">
Filter 6/18-6/19 does not display items created on 6/19
<img width="1062" alt="screen shot 2016-06-19 at 10 40 16 am" src="https://cloud.githubusercontent.com/assets/15206696/16177991/75202c34-360a-11e6-93d8-99bb49dad5e6.png">
Start Date is Inclusive
<img width="1058" alt="screen shot 2016-06-19 at 10 42 16 am" src="https://cloud.githubusercontent.com/assets/15206696/16177993/8f475498-360a-11e6-9aea-a3acd65aca1a.png">

**Comment by armahillo** [comment]
This is a known behavior of ActiveAdmin, though I am in agreement it should be addressed.

https://github.com/activeadmin/activeadmin/issues/2387 (see also: https://github.com/activeadmin/activeadmin/issues/2374 )

There are patches shown in both.

**Comment by armahillo** [comment]
See previous commit -- this issue has been fixed!
