### ISSUE TITLE
Add Graphs / Charts to Dashboard

### ISSUE THREAD

**Issue by tmobaird** [rubyforgood/pdx_diaper#53]
Hey peeps 🐤, I'm updating the dashboard page a bit and I wanted to know if you all have any suggestions about the types of charts that we should display. Here are some of the examples I have so far for the donations:

<img width="454" alt="screen shot 2016-06-20 at 11 58 48 pm" src="https://cloud.githubusercontent.com/assets/7366444/16217632/3caa2c3a-3743-11e6-8c78-1c2dfdff50a9.png">

<img width="454" alt="screen shot 2016-06-20 at 11 59 10 pm" src="https://cloud.githubusercontent.com/assets/7366444/16217628/3703f824-3743-11e6-8c85-aee1f9d578cc.png">

Any ideas?

Also, I'm using [chartkick](http://chartkick.com/) if any of you all want to check out how it works.

**Comment by armahillo** [comment]
Nice!!

A couple charts I think Rachel would probably like:
- A bar chart showing current totals of all different type of item across all locations (so she knows if she's getting low on something) -- bonus points if its a stacked bar graph where each layer is a different location
- A line chart that shows donation totals vs. ticket totals -- this will require some complicated AREL querying. LMK if you want an assist (start with a test :) )

The ones you show above look good too. I don't thinks he has _any_ charts right now, so just put up some ones you can think of and we can tell her that this is something we can change over time. 

Nice work! Those are sweet!

**Comment by tmobaird** [comment]
@armahillo How's this look for the bar chart? 

<img width="454" alt="screen shot 2016-06-21 at 11 02 58 pm" src="https://cloud.githubusercontent.com/assets/7366444/16253405/5d81f1c4-3804-11e6-8b07-ddec14a311ec.png">

 You can hover over the bars and see the exact totals as well.

I'll tackle the line chart over the next few days. I might need some help with that at some point 😬

**Comment by armahillo** [comment]
DUDE.

perfect.

**Comment by tmobaird** [comment]
@armahillo ![image](https://cdn.meme.am/instances/500x/51576797.jpg)

**Comment by armahillo** [comment]
Fun thing I learned yesterday, if you reference "Issue #XXXX" in your commit message, when you push Github will automatically tag that issue with the a commit note. You can even reference multiple commits! :)

**Comment by armahillo** [comment]
@tmobaird Do you think this issue has been resolved with your recent commit, or is there more that needs to be added still?

**Comment by tmobaird** [comment]
@armahillo the only thing that needs to be added is the line chart for donation vs. ticket totals. You can close out this issue if you want, and I can create a separate issue for that one though.

**Comment by armahillo** [comment]
Seems like it fits with this issue. :)

When you do your next commit, include "Issue #53" somewhere in the commit message and it'll tag it here

**Comment by tmobaird** [comment]
Sounds good, will do! :+1:

**Comment by christine-sm** [comment]
@armahillo that is really cool how you can link the commits and issues 😎 . @tmobaird the charts look great!!

**Comment by armahillo** [comment]
@cmmovius IKR? I found out by accident while patching the issues you created yesterday. :)  magical git-hooks!

**Comment by tmobaird** [comment]
![magic](http://s2.quickmeme.com/img/40/4054c9dfdce4b53c094010582496c2bb8e7a8944d3315bff05dd7327b4c7a3e3.jpg)

Great git tip! And thanks @cmmovius!! Chartkick really made adding them super easy!

**Comment by pdxdiaperbank** [comment]
@tmobaird - 
We LOVE all of the charts!! Any chance we can add them all?? Data is SO important for nonprofits. We use these statistics for our annual report, marketing, fundraising, and grant writing. This would be so fantastic!!

~Rachel

**Comment by tmobaird** [comment]
@pdxdiaperbank Hey Rachel, thanks a ton for that!! I'm glad to hear it!

I can add more charts for the rest of the data ASAP. Are there any specific statistics you would like to request to be displayed in a chart?

**Comment by pdxdiaperbank** [comment]
@tmobaird Thanks, Thomas!  Let me give this a little more thought and get back to you shortly. One thing I can think of on the top of my head is a quick "snapshot" on the dashboard of items ticketed/received (this is a screenshot of my current dashboard in this capacity. I look at it a lot. It's very helpful reference  throughout the year to be sure we are meeting our diaper distribution goals).  

![screenshot 2016-07-05 11 22 21](https://cloud.githubusercontent.com/assets/20074085/16595224/fe1a92d2-42a2-11e6-8291-d5a75770afbe.png)
![screenshot 2016-07-05 11 22 39](https://cloud.githubusercontent.com/assets/20074085/16595225/fe1afe84-42a2-11e6-9462-bb80fe1c4015.png)

Also, any chance on being able to click on each graph to enlarge?  I'd love the ability to at least take a screenshot of the image in order to print it or add to another document...

**Comment by tmobaird** [comment]
@pdxdiaperbank that's perfect, I'll start adding the "snapshot" of items to the dashboard. 

In regards to enlarging, this should definitely be possible. I will look into adding this and possibly a download functionality for the charts, so you have the ability to print them.

Thanks!!

**Comment by pdxdiaperbank** [comment]
@tmobaird You Rock. I am working outside the office this week, however, when I return I will gather some ideas I have there about graph/chart possibilities that would be helpful. Thanks, Rachel

**Comment by pdxdiaperbank** [comment]
@tmobaird , I've created a ticket in the database, however, I noticed that no data popped up on the dashboard graph for tickets. Is that something that you are currently working on? I wanted to ask before I created it as a separate issue. Thanks!

**Comment by tmobaird** [comment]
@pdxdiaperbank yep, it's something I'm working on! I should have that up in the next few days!

**Comment by armahillo** [comment]
@tmobaird Is that dashboard graph for tickets the one covered by #68 ? I don't want to hold that up -- I'll do the database config commits in a separate commit.

**Comment by tmobaird** [comment]
@armahillo nope! it's a separate one that I should have knocked out by today or tomorrow

**Comment by pdxdiaperbank** [comment]
Thanks, @tmobaird and @armahillo!!

![t hanks](https://cloud.githubusercontent.com/assets/20074085/16740385/bc62e028-4753-11e6-9e3e-f7be594aea9e.jpeg)

**Comment by armahillo** [comment]
@tmobaird Sounds good! I'll be on the lookout. I just merged #68 and am working on DB config issues now. Should have that finalized soon I think.

**Comment by armahillo** [comment]
Just realized this change wasn't yet deployed! Just deployed it and graphs are showing up in dashboard. Looks awesome.

I think we're all good here now, right @tmobaird ?

**Comment by tmobaird** [comment]
@armahillo yep! 👍 If @pdxdiaperbank has requests for any additional charts in the future, we can just create more specific issues for those
