### ISSUE TITLE
N+1 Behavior with Diaper Drive totals by day helper

### ISSUE THREAD

**Issue by armahillo** [rubyforgood/pdx_diaper#63]
in `dashboard.rb`:

```
####
# TODO: These generate a bunch of individual counts because it's querying day by day.
# Not sure how to group the day results together to avoid n+1 but it's worth
# exploring that to make this query more efficient.
####
render partial: 'metrics/charts', locals: { :start_date => start, :end_date => date_end }
```

and that partial has: 

```
<% split_range_into_dates(start_date, end_date).each do |day| %>
    <% test[day] = diaper_drives_total(start_date, day).count %>
<% end %>
```

I'm not sure there's a way to collapse this query to be more efficient -- can you group_by created_at, extracting it out by day? 

This isn't a critical fix -- other queries on dashboard have been tuned so this is OK, but we should fix it in next version.

**Comment by cattywampus** [comment]
Yes you can. The trick is to use the database's `date` functions to create new columns that format your timestamped field to use any date representation you want (year, month, day, hour, etc). Placing this in your `#select` call and providing a custom name makes it available to your `#group` clause. This makes it possible to do fun things like count transactions by day or view daily trends averaged over time and grouped by hour. Here's a snippet of what a query _might_ look like:

```
Donation.select("source, date(created_at, '%Y-%m-%d') as created_date").where(created_at: start..end).group("created_date, source").count
```

This is untested, but if it were to work it would query all donations between `start` and `end` and group them by their day first, and then group by sources. I think it gets the idea across. If it's alright, I can assign this to myself and tackle it tonight.

**Comment by cattywampus** [comment]
Food for thought: As we start to use database functions, we need to be conscientious about using vendor specific functionality. Since our dev/test databases are sqlite3 and our production database is PostgreSQL there is a possible risk that changes like this might not be portable between database providers. 

Since this is a simple date function I doubt we run much risk of that, but it's worth keeping in the back of our minds. We should probably consider converting to PostgreSQL for dev and test environments to ensure consistency.

**Comment by armahillo** [comment]
@cattywampus Good point re: vendor-specific DB functions. I had done sqlite3 initially so we could not have to sweat doing DB config on all the machines -- makes sense to move towards something more reliable by making it PG across the board, though.

**Comment by cattywampus** [comment]
@armahillo do we have any more N+1 query issues or optimizations to make? If not, since PR #67 was merged then we should close this out.

**Comment by armahillo** [comment]
We're solid, AFAICT. Nice work :)
