### ISSUE TITLE
Inventory Transfers

### ISSUE THREAD

**Issue by pdxdiaperbank** [rubyforgood/pdx_diaper#66]
Hi all,

*I would rate this request as very important. 

PDX Diaper Bank must be able to transfer inventory from one storage location to another. Being able to scan the item barcodes onto the system for the transfer would be a huge time saver as well. The following details should be noted in the system for each transaction:

1) Date of transfer
2) Location the items are be transferred from
3) Location the items are being transferred to
4) The item name, size, and quantity

Thank you,
Rachel
(971)258-2883

**Comment by armahillo** [comment]
@pdxdiaperbank These transfers are different than when you disburse diaper packages through "Tickets" right?

**Comment by pdxdiaperbank** [comment]
@armahillo ,
Exactly right. Tickets remove the items from inventory all together (those are the diapers that we distribute to our partner agencies/families in need). Transfers would shift the items from one storage location to another, while still leaving them in inventory. Inventory transfers happen pretty regularly. For instance, I just transferred about 10,000 diapers from our bulk storage location (Arborscape) to our main office a couple days ago.

**Comment by cattywampus** [comment]
Has anyone started working on this? I don't see anyone assigned, and since it's scheduled for MVP it should get started immediately. I'll pick this up unless someone else has started it or wants to tackle it. Let me know.

**Comment by armahillo** [comment]
@cattywampus Go for it! I've got a couple that I'm working on right now but hadn't started on this one. Feel free!

**Comment by pdxdiaperbank** [comment]
Thanks for tackling this, @cattywampus !

**Comment by pdxdiaperbank** [comment]
Hi @cattywampus ,  Just a friendly follow-up on the progress conducting inventory transfers... Do we have a estimated completion date for this?  I had a large inventory transfer a couple weeks back and in order for me to create my invoices for our most recent diaper distributions to our partner agencies, the  information from the transfer has to be entered first... Thanks!

**Comment by armahillo** [comment]
If @cattywampus can't get to it, I should have some time later this week. I'm finishing up a contract this week. :)

**Comment by pdxdiaperbank** [comment]
Thanks, @armahillo!

**Comment by seanmarcia** [comment]
I've started on this. The first pass I'm making is similar to how tickets work since I don't currently have access to a barcode scanner and I want to get something out the door as soon as possible. We'll add in the barcode functionality into the Mark 2 milestone. :)

**Comment by armahillo** [comment]
I dig it! Thanks @seanmarcia 

I forget which issue it was, but I suggested making the barcode scanner code a partial that we can import in multiple places, since it would already be useful in 2 places, and this would be a third one. That can be mk2 feature tho for sure. :D

**Comment by seanmarcia** [comment]
I also created an in-progress label in case people want to label things that are being worked on :)

**Comment by pdxdiaperbank** [comment]
Thanks for chipping away at all of this, everyone! I'm just settling back in from an "off the grid" vacation w/o WIFI, so I'm just catching up on things.... How's it going? Anything you need from me?

**Comment by seanmarcia** [comment]
I pushed the branch `inventory_transfer` that will close this issue. It _heavily_ borrows from the ticket model/controller/etc and should be refactored.

**Comment by armahillo** [comment]
Awesome, thanks Sean!

**Comment by armahillo** [comment]
@seanmarcia TY for the heads up about the refactoring. If it works for now that's good enough to get MVP done.
