### ISSUE TITLE
Donation Source List

### ISSUE THREAD

**Issue by pdxdiaperbank** [rubyforgood/pdx_diaper#70]
Hi all,

This _should_ be a quick fix--
When creating a new donation, I am given a drop-down menu with source list-- Is it possible to make this list editable? At a minimum, it would be great if we could add "Misc. Donation" to the list; sometimes the sources in which we received donations don't always fit into the three categories that are there. Thank you!! :)

![screenshot 2016-07-11 09 15 34](https://cloud.githubusercontent.com/assets/20074085/16737908/54e8dbba-4748-11e6-899f-bafa5796f326.png)

**Comment by armahillo** [comment]
I got this.

Would you expect to find this as a menu item under "Donations" or under "Inventory"?

**Comment by pdxdiaperbank** [comment]
@armahillo , Probably under the inventory menu button just because that is where all of the editable lists seem to be.

**Comment by seanmarcia** [comment]
I tweaked the `donation.rb` to add "Misc. Donation" and the quick fix is ready to go and already in master. Maybe we should make it part of the Mark 2 stretch goal of making it an editable field.

**Comment by armahillo** [comment]
> Maybe we should make it part of the Mark 2 stretch goal of making it an editable field.

@seanmarcia I like this idea! I'll create the issue and tag it Mark 2, and reference your comment.

This issue appears to be resolved with your commit. Thanks!
