### ISSUE TITLE
Alphabetize All Drop-down Menus

### ISSUE THREAD

**Issue by pdxdiaperbank** [rubyforgood/pdx_diaper#83]
Hi @armahillo and all,

Please alphabetize all drop-down menus in the database to make it easier to spot the item we're looking for. Right now, it shuffles the the items around based upon popularity/use, which makes it difficult to easily locate an item. 

Thanks! 
Rachel

**Comment by seanmarcia** [comment]
Which dropdown menus?

I'm not super familiar with the App so I want to make sure I'm sorting the right stuff! :)

**Comment by pdxdiaperbank** [comment]
Honestly, all of them would be phenomenal. But most importantly: the drop down inventory list when inputting a donation and the list when entering a donation. :) 

Thanks,
Rachel

**Comment by cubadomingo** [comment]
I'd love to tackle this if possible!

**Comment by pdxdiaperbank** [comment]
Oops. Sorry, I meant to say the inventory drop-down menus on both the ticketing page and the donation page.  

Rachel

**Comment by armahillo** [comment]
@cubadomingo Go for it! Put in a PR when you're ready and I'll review it & re-deploy within 24H.
